# Generated by Django 2.2 on 2019-06-24 11:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_subtitle', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'MainIndex Page',
                'verbose_name_plural': 'MainIndex Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
