# Generated by Django 2.2 on 2019-06-24 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabstructure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainIndexPage',
            new_name='MainPage',
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Main Page', 'verbose_name_plural': 'Main Pages'},
        ),
    ]
