# Generated by Django 2.2 on 2019-06-24 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tabstructure', '0002_auto_20190624_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='MainIndexPage',
        ),
        migrations.AlterModelOptions(
            name='mainindexpage',
            options={'verbose_name': 'MainIndex Page', 'verbose_name_plural': 'MainIndex Pages'},
        ),
    ]
