# Generated by Django 2.2 on 2019-06-24 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('tabstructure', '0004_mainpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='IOS',
        ),
        migrations.AlterModelOptions(
            name='ios',
            options={'verbose_name': 'IOS Page', 'verbose_name_plural': 'IOS Pages'},
        ),
        migrations.RenameField(
            model_name='ios',
            old_name='main_title',
            new_name='ios_title',
        ),
    ]
