# Generated by Django 2.2 on 2019-06-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('tabstructure', '0007_ios_ios_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeJS',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nodejs_title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'NodeJS Page',
                'verbose_name_plural': 'NodeJS Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
