# Generated by Django 2.2 on 2019-06-25 05:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabstructure', '0008_nodejs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ios',
            name='content',
            field=wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True),
        ),
    ]
