# Generated by Django 2.2 on 2019-06-25 05:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabstructure', '0010_auto_20190625_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodejs',
            name='content',
            field=wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='python',
            name='content',
            field=wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True, null=True),
        ),
    ]
