# Generated by Django 2.2 on 2019-06-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabstructure', '0011_auto_20190625_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ios',
            old_name='ios_subtitle',
            new_name='ios_content_detail',
        ),
    ]
