# Generated by Django 2.2 on 2019-06-25 08:48

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabstructure', '0013_auto_20190625_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainindexpage',
            name='subpage_subtitle',
            field=wagtail.core.fields.RichTextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainindexpage',
            name='subpage_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
