# Generated by Django 2.2 on 2019-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('tabstructure', '0014_auto_20190625_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('android_title', models.CharField(max_length=255, null=True)),
                ('android_content_detail', models.CharField(max_length=255, null=True)),
                ('android_extra_detail', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('content', wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Android Page',
                'verbose_name_plural': 'Android Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('react_title', models.CharField(max_length=255, null=True)),
                ('react_content_detail', models.CharField(max_length=255, null=True)),
                ('react_extra_detail', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('content', wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'React Page',
                'verbose_name_plural': 'React Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Ruby',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('ruby_title', models.CharField(max_length=255, null=True)),
                ('ruby_content_detail', models.CharField(max_length=255, null=True)),
                ('ruby_extra_detail', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('content', wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=255, required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ruby Page',
                'verbose_name_plural': 'Ruby Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
