# Generated by Django 2.2 on 2019-06-25 12:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('tabstructure', '0015_android_react_ruby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodejs',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='python',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='react',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='ruby',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='ios',
            name='content',
            field=wagtail.core.fields.StreamField([('raw_content', wagtail.core.blocks.StructBlock([('raw_content', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML content', max_length=1024, required=True))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Android',
        ),
        migrations.DeleteModel(
            name='NodeJS',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='React',
        ),
        migrations.DeleteModel(
            name='Ruby',
        ),
    ]
