# Generated by Django 2.2 on 2019-06-25 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('tabstructure', '0016_auto_20190625_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOS',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language Page', 'verbose_name_plural': 'Language Pages'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='ios_content_detail',
            new_name='language_content_detail',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='ios_extra_detail',
            new_name='language_extra_detail',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='ios_title',
            new_name='language_title',
        ),
    ]
